print("Welcome to the tip calculator")
total_bill=float(input("What was the total bill? $"))
percent_tip=int(input("what percentage tip would you like to give? 10, 12, or 15? "))
no_of_people=int(input("How many people to split the bill? "))
total_tip=round((percent_tip/100)*total_bill,2)
each_share=round((total_tip+total_bill)/7,2)
print(f"Each person should pay: ${each_share}")